linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US
  varnamelen:
    min-name-length: 2

linters:
  enable-all: true
  disable:
    - varnamelen
    - depguard

issues:
    exclude-rules:
      - path: _test\.go
        text: "does not use range value in test Run"
        linters:
          - paralleltest
      - path: _test\.go
        linters:
          - varnamelen
