sudo: false

language: go
go:
  - 1.8.5
  - 1.9.2
  - tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep github.com/golang/lint/golint honnef.co/go/tools/cmd/staticcheck

install:
  - dep ensure

before_script:
  - go vet
  - golint -set_exit_status=1
  - staticcheck

script:
  - echo mode:$' 'atomic > coverage.txt
  - go list ./... | egrep -v vendor | xargs -n1 -I{} sh -c 'go test -race -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.txt' && rm coverage.tmp

after_success:
  - bash <(curl -s https://codecov.io/bash)
