sudo: false

language: go
go:
  - 1.7.6
  - 1.8.3
  - tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep github.com/golang/lint/golint honnef.co/go/tools/cmd/staticcheck

install:
  - dep ensure

before_script:
  - go vet
  - golint -set_exit_status=1
  - staticcheck

script:
  - go test -v -race -cover ./...
