[[constraint]]
  branch = "master"
  name = "github.com/ikawaha/kagome.ipadic"

[[constraint]]
  branch = "master"
  name = "github.com/irfansharif/cfilter"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "master"
  name = "golang.org/x/text"
